version: "3.9"
services:
  ### Prefect Database
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["server"]

  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:3.1.14-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["server"]

  ### Prefect CLI
  # cli:
  #   image: prefecthq/prefect:2.11.5-python3.11
  #   entrypoint: "bash"
  #   working_dir: "/root/flows"
  #   volumes:
  #     - "./prefect:/root/flows"
  #   environment:
  #     - PREFECT_API_URL=http://server:4200/api
  #     # - PREFECT_API_KEY=cli-7d85f538-d6ca-4c97-8393-b31b80382c1e
  #   profiles: ["cli"]
      
volumes:
  prefect:
  db:
networks:
  default:
    name: prefect-network