#!/bin/bash

# =============================================================================
# Corduroy EC2 Deployment Script
# =============================================================================
# This script pushes your frontend and backend code to an EC2 instance.
# 
# Usage:
#   ./ec2-deploy.sh                    # Deploy using saved config
#   ./ec2-deploy.sh --setup            # First-time setup (saves EC2 details)
#   ./ec2-deploy.sh --full             # Full deploy (code + restart services)
#   ./ec2-deploy.sh --code-only        # Only sync code, don't restart
#
# Prerequisites:
#   - SSH key for EC2 instance
#   - EC2 instance running with SSH access
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration file
CONFIG_FILE=".ec2-deploy.conf"

# Default values
REMOTE_DIR="/home/ubuntu/corduroy"

print_header() {
    echo -e "${CYAN}================================================${NC}"
    echo -e "${CYAN}     Corduroy EC2 Deployment Tool              ${NC}"
    echo -e "${CYAN}================================================${NC}"
    echo
}

print_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo
    echo "Options:"
    echo "  --setup           Configure EC2 connection details (run once)"
    echo "  --full            Full deployment: sync code + restart services"
    echo "  --code-only       Only sync code, don't restart services"
    echo "  --restart         Only restart services (no code sync)"
    echo "  --status          Check status of services on EC2"
    echo "  --logs [service]  View logs (backend, frontend, nginx)"
    echo "  --ssh             SSH into the EC2 instance"
    echo "  --help            Show this help message"
    echo
    echo "Examples:"
    echo "  $0 --setup                # First-time setup"
    echo "  $0 --full                 # Full deployment"
    echo "  $0 --code-only            # Quick code sync"
    echo "  $0 --logs backend         # View backend logs"
    echo
}

# Load configuration
load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
        return 0
    else
        return 1
    fi
}

# Save configuration
save_config() {
    cat > "$CONFIG_FILE" << EOF
# EC2 Deployment Configuration
# Generated by ec2-deploy.sh

EC2_HOST="$EC2_HOST"
EC2_USER="$EC2_USER"
SSH_KEY="$SSH_KEY"
REMOTE_DIR="$REMOTE_DIR"
EOF
    chmod 600 "$CONFIG_FILE"
    echo -e "${GREEN}Configuration saved to $CONFIG_FILE${NC}"
}

# Setup wizard
run_setup() {
    echo -e "${YELLOW}EC2 Deployment Setup${NC}"
    echo -e "${BLUE}Please provide your EC2 connection details:${NC}"
    echo
    
    # EC2 Host
    read -p "EC2 Public IP or DNS: " EC2_HOST
    if [ -z "$EC2_HOST" ]; then
        echo -e "${RED}ERROR: EC2 host is required${NC}"
        exit 1
    fi
    
    # EC2 User (default: ubuntu)
    read -p "EC2 Username [ubuntu]: " EC2_USER
    EC2_USER=${EC2_USER:-ubuntu}
    
    # SSH Key path
    read -p "Path to SSH key file: " SSH_KEY
    # Expand tilde to home directory
    SSH_KEY="${SSH_KEY/#\~/$HOME}"
    if [ ! -f "$SSH_KEY" ]; then
        echo -e "${RED}ERROR: SSH key file not found: $SSH_KEY${NC}"
        exit 1
    fi
    
    # Remote directory
    read -p "Remote directory [/home/ubuntu/corduroy]: " REMOTE_DIR
    REMOTE_DIR=${REMOTE_DIR:-/home/ubuntu/corduroy}
    
    # Test connection
    echo
    echo -e "${YELLOW}Testing SSH connection...${NC}"
    if ssh -i "$SSH_KEY" -o ConnectTimeout=10 -o StrictHostKeyChecking=no "$EC2_USER@$EC2_HOST" "echo 'Connection successful!'" 2>/dev/null; then
        echo -e "${GREEN}✓ SSH connection successful${NC}"
    else
        echo -e "${RED}✗ SSH connection failed. Please check your settings.${NC}"
        exit 1
    fi
    
    save_config
    echo
    echo -e "${GREEN}Setup complete! You can now run:${NC}"
    echo -e "  ${CYAN}$0 --full${NC}     # Full deployment"
}

# Validate configuration
validate_config() {
    if ! load_config; then
        echo -e "${RED}ERROR: No configuration found. Run '$0 --setup' first.${NC}"
        exit 1
    fi
    
    if [ -z "$EC2_HOST" ] || [ -z "$EC2_USER" ] || [ -z "$SSH_KEY" ]; then
        echo -e "${RED}ERROR: Invalid configuration. Run '$0 --setup' to reconfigure.${NC}"
        exit 1
    fi
    
    if [ ! -f "$SSH_KEY" ]; then
        echo -e "${RED}ERROR: SSH key not found: $SSH_KEY${NC}"
        exit 1
    fi
}

# SSH command helper
ssh_cmd() {
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "$EC2_USER@$EC2_HOST" "$@"
}

# SCP command helper
scp_cmd() {
    scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$@"
}

# Rsync command helper
rsync_cmd() {
    rsync -avz --progress -e "ssh -i $SSH_KEY -o StrictHostKeyChecking=no" "$@"
}

# Sync code to EC2
sync_code() {
    echo -e "${YELLOW}Syncing code to EC2...${NC}"
    
    # Create remote directory if it doesn't exist
    ssh_cmd "mkdir -p $REMOTE_DIR"
    
    # Sync backend
    echo -e "${BLUE}Syncing backend...${NC}"
    rsync_cmd \
        --exclude '__pycache__' \
        --exclude '*.pyc' \
        --exclude '.pytest_cache' \
        ./backend/ "$EC2_USER@$EC2_HOST:$REMOTE_DIR/backend/"
    
    # Build frontend locally
    echo -e "${BLUE}Building frontend locally...${NC}"
    cd frontend
    yarn build
    cd ..
    
    # Sync frontend source (exclude node_modules and .next)
    echo -e "${BLUE}Syncing frontend source...${NC}"
    rsync_cmd \
        --exclude 'node_modules' \
        --exclude '.next' \
        --exclude '.turbo' \
        ./frontend/ "$EC2_USER@$EC2_HOST:$REMOTE_DIR/frontend/"
    
    # Sync the standalone build (includes its own node_modules)
    echo -e "${BLUE}Syncing standalone build...${NC}"
    rsync_cmd \
        ./frontend/.next/standalone/ "$EC2_USER@$EC2_HOST:$REMOTE_DIR/frontend/.next/standalone/"
    
    # Sync static assets
    rsync_cmd \
        ./frontend/.next/static/ "$EC2_USER@$EC2_HOST:$REMOTE_DIR/frontend/.next/static/"
    
    # Setup standalone assets on EC2
    echo -e "${BLUE}Setting up standalone assets on EC2...${NC}"
    ssh_cmd "cd $REMOTE_DIR/frontend && cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/"
    
    # Sync configuration files
    echo -e "${BLUE}Syncing configuration files...${NC}"
    scp_cmd requirements.lock "$EC2_USER@$EC2_HOST:$REMOTE_DIR/"
    scp_cmd nginx.conf "$EC2_USER@$EC2_HOST:$REMOTE_DIR/"
    scp_cmd ec2-setup.sh "$EC2_USER@$EC2_HOST:$REMOTE_DIR/"
    scp_cmd ec2-services.sh "$EC2_USER@$EC2_HOST:$REMOTE_DIR/"
    
    # Sync systemd service files
    ssh_cmd "mkdir -p $REMOTE_DIR/systemd"
    scp_cmd systemd/corduroy-backend.service "$EC2_USER@$EC2_HOST:$REMOTE_DIR/systemd/"
    scp_cmd systemd/corduroy-frontend.service "$EC2_USER@$EC2_HOST:$REMOTE_DIR/systemd/"
    
    echo -e "${GREEN}✓ Code sync complete${NC}"
}

# Restart services on EC2
restart_services() {
    echo -e "${YELLOW}Restarting services on EC2...${NC}"
    
    ssh_cmd "cd $REMOTE_DIR && sudo bash ec2-services.sh restart"
    
    echo -e "${GREEN}✓ Services restarted${NC}"
}

# Check service status
check_status() {
    echo -e "${YELLOW}Checking service status on EC2...${NC}"
    echo
    
    ssh_cmd "cd $REMOTE_DIR && sudo bash ec2-services.sh status"
}

# View logs
view_logs() {
    local service=$1
    
    case "$service" in
        "backend")
            ssh_cmd "sudo journalctl -u corduroy-backend -f --no-pager -n 50"
            ;;
        "frontend")
            ssh_cmd "sudo journalctl -u corduroy-frontend -f --no-pager -n 50"
            ;;
        "nginx")
            ssh_cmd "sudo tail -f /var/log/nginx/access.log /var/log/nginx/error.log"
            ;;
        *)
            echo -e "${RED}Unknown service: $service${NC}"
            echo "Available services: backend, frontend, nginx"
            exit 1
            ;;
    esac
}

# Full deployment
full_deploy() {
    echo -e "${YELLOW}Starting full deployment...${NC}"
    echo
    
    sync_code
    
    echo
    echo -e "${YELLOW}Installing dependencies and restarting services...${NC}"
    ssh_cmd "cd $REMOTE_DIR && sudo bash ec2-services.sh deploy"
    
    echo
    echo -e "${GREEN}================================================${NC}"
    echo -e "${GREEN}  Deployment Complete!                          ${NC}"
    echo -e "${GREEN}================================================${NC}"
    echo
    echo -e "Your app should now be running at:"
    echo -e "  ${CYAN}http://$EC2_HOST${NC}"
    echo
    echo -e "API endpoint:"
    echo -e "  ${CYAN}http://$EC2_HOST/graphql${NC}"
    echo
}

# SSH into instance
ssh_into() {
    echo -e "${YELLOW}Connecting to EC2 instance...${NC}"
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "$EC2_USER@$EC2_HOST"
}

# Main script logic
print_header

case "${1:-}" in
    "--setup")
        run_setup
        ;;
    "--full")
        validate_config
        full_deploy
        ;;
    "--code-only")
        validate_config
        sync_code
        ;;
    "--restart")
        validate_config
        restart_services
        ;;
    "--status")
        validate_config
        check_status
        ;;
    "--logs")
        validate_config
        if [ -z "$2" ]; then
            echo -e "${RED}ERROR: Please specify a service (backend, frontend, nginx)${NC}"
            exit 1
        fi
        view_logs "$2"
        ;;
    "--ssh")
        validate_config
        ssh_into
        ;;
    "--help"|"-h"|"")
        print_usage
        ;;
    *)
        echo -e "${RED}ERROR: Unknown option: $1${NC}"
        echo
        print_usage
        exit 1
        ;;
esac

