CREATE USER IF NOT EXISTS "lambda-service-account" IDENTIFIED BY "***";
GRANT CREATE TEMPORARY TABLES, DELETE, EXECUTE, INSERT, LOCK TABLES, SELECT, SHOW VIEW, UPDATE ON cwpdb.* TO 'lambda-service-account';
